<?php include 'header.php';?>
    <div class="single-blog-wrapper">
        <div class="single-blog-content-wrapper d-flex">

            <div class="single-blog--text">
                <h2>Kebijakan Privasi Kuskus Group Ltd.</h2>
                <p>Kuskus.com may collect personal identification information from users in a variety of ways, including, but not limited to, when users visit our website, register on the site, place an order, and in connection with other activities, services, features or resources we make available on our website. Users may be asked for, as appropriate, name, email address, mailing address, phone number. Users may, however, visit our site anonymously. We will collect personal identification information from users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain website related activities. You may also have the ability to update or remove your Personal Information by logging into the website and editing your Personal Information within your profile (to the extent one exists). However, archival or backup copies of said information will not cease to exist and our shall not be liable for any problems in this editing process. Information collected is used to provide and maintain the website and is used at our's discretion. This Information can also be used to contact you to further discuss interest in our company, the services we provide, and to send information regarding us, its partners, its products and other activities such as promotions and events. You may be invited to receive email correspondence by providing an email address. Your email address and any Personal Information will not be distributed or shared with third parties unless it is to transact such business as you have contracted us to do, to comply with legal processes and/or law enforcement requests, or to conduct any business as KusKus, in its sole discretion, deems reasonable. KusKus may also email (or send via other methods) information regarding updates to the website, newsletters, advertisements, or other correspondence. You will have an opportunity to unsubscribe to any emails or mailings by clicking on an "unsubscribe" hyperlink contained in such promotional emails or contact us by email at privacy@kuskus.com. Despite unsubscribing from such list, KusKus may send confirmation emails if you order online and may need to contact you by phone, email or regular mail with questions or issues concerning your order. Any opt-out by you is not deemed valid until processed by KusKus Group. We shall not be liable for problems arising from the opt-out procedure. KusKus acknowledge that you have the right to control how your Personal Information is collected and used.</p>
                <blockquote>
                    <h6><i class="fa fa-quote-left" aria-hidden="true"></i> Jika kamu memiliki kegagalan, jangan mundur, maju dan carilah semua kesalahanmu hingga semuanya habis.</h6>
                    <span>Jack Ma</span>
                </blockquote>
            </div>
        </div>
    </div>
<?php include 'footer.php';?>
